### PR TITLE
Use lexical-binding in parseclj-lex.el as well

### PR DESCRIPTION
**Pull request by tarsius**

### CODE REVIEW

**Comment by vemv** [comment]
Thanks for the PR!

While I'd imagine that this would pass 99 out of 100 times, I would err on the side of cautiousness and leave it as-is.

Especially as parseclj/parseedn move at a slower pace.

**Comment by vemv** [comment]
Got it, TIL. Feel free to add it and I'll merge it in!

**Comment by tarsius** [comment]
Ups, one moment please.

**Comment by tarsius** [comment]
Good to go now :grin:

**Comment by vemv** [comment]
Thanks!

I'll cut a release. A stable CIDER release including it may not be created until later next week.

**Pull request merged**
